name: flutter_web_bluetooth
description: A library to use the web bluetooth api in your web project. Will play nice if used in IO projects.
version: 0.0.8
publish_to: none

environment:
  sdk: ">=2.12.0"

platforms:
  web:

dependencies:
  js: '>=0.6.3'
  meta: '>=1.3.0'
  logging: '>=1.0.0'

dev_dependencies:
  test: ^1.20.1
  lints: ^1.0.1
